const K="inzaki_charcoal_v2";let S=JSON.parse(localStorage.getItem(K)||'{"raw":[],"batches":[],"sales":[],"expenses":[]}');const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),today=new Date().toISOString().slice(0,10);$$('input[type=date]').forEach(x=>x.value=today);
const rp=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(+n||0), kg=n=>(+n||0).toLocaleString('id-ID',{maximumFractionDigits:2})+' kg',esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function save(){localStorage.setItem(K,JSON.stringify(S));render()}function rawStock(id){let r=S.raw.find(x=>x.id==id);return r?+r.qty:0}function sold(bid){return S.sales.filter(x=>x.batchId==bid).reduce((a,x)=>a+x.qty,0)}function batch(id){return S.batches.find(x=>x.id==id)}
function render(){
 let rawVal=S.raw.reduce((a,x)=>a+x.qty*x.price,0),out=S.batches.reduce((a,x)=>a+x.output,0),inp=S.batches.reduce((a,x)=>a+x.input,0),sales=S.sales.reduce((a,x)=>a+x.total,0),loss=inp-out;
 let cogs=S.sales.reduce((a,x)=>{let b=batch(x.batchId);return a+(b?x.qty*b.hppkg:0)},0),other=S.expenses.reduce((a,x)=>a+x.amount,0);
 $('#dRaw').textContent=rp(rawVal);$('#dFinished').textContent=kg(out-S.sales.reduce((a,x)=>a+x.qty,0));$('#dSales').textContent=rp(sales);$('#dProfit').textContent=rp(sales-cogs-other);
 $('#dInput').textContent=kg(inp);$('#dOutput').textContent=kg(out);$('#dLoss').textContent=kg(loss);$('#dLossPct').textContent=(inp?loss/inp*100:0).toFixed(1)+'%';
 $('#rawTable').innerHTML=S.raw.map(r=>`<tr><td>${esc(r.name)}</td><td>${kg(r.qty)}</td><td>${rp(r.qty*r.price)}</td><td>${esc(r.supplier||'-')}</td></tr>`).join('')||empty(4);
 $('#rawSelect').innerHTML=S.raw.filter(r=>r.qty>0).map(r=>`<option value="${r.id}">${esc(r.name)} — ${kg(r.qty)} @ ${rp(r.price)}/kg</option>`).join('');
 $('#batchTable').innerHTML=S.batches.slice().reverse().map(b=>`<tr><td>${b.code}</td><td>${b.date}</td><td>${esc(b.rawName)}</td><td>${kg(b.input)}</td><td>${kg(b.output)}</td><td>${kg(b.loss)} (${b.lossPct.toFixed(1)}%)</td><td>${rp(b.totalHpp)}</td><td>${rp(b.hppkg)}</td></tr>`).join('')||empty(8);
 $('#salesBatch').innerHTML=S.batches.filter(b=>b.output-sold(b.id)>0).map(b=>`<option value="${b.id}">${b.code} — sisa ${kg(b.output-sold(b.id))} — HPP ${rp(b.hppkg)}/kg</option>`).join('');
 let tq=0,tv=0;$('#finishedTable').innerHTML=S.batches.map(b=>{let q=b.output-sold(b.id);tq+=q;tv+=q*b.hppkg;return `<tr><td>${b.code}</td><td>${esc(b.rawName)}</td><td>${kg(b.output)}</td><td>${kg(sold(b.id))}</td><td>${kg(q)}</td><td>${rp(b.hppkg)}</td></tr>`}).join('')||empty(6);
 $('#fQty').textContent=kg(tq);$('#fValue').textContent=rp(tv);$('#fAvg').textContent=rp(tq?tv/tq:0);
 $('#salesTable').innerHTML=S.sales.slice().reverse().map(x=>{let b=batch(x.batchId),c=x.qty*(b?b.hppkg:0);return `<tr><td>${x.date}</td><td>${b?.code||'-'}</td><td>${esc(x.customer)}</td><td>${kg(x.qty)}</td><td>${rp(x.total)}</td><td>${rp(c)}</td><td>${rp(x.total-c)}</td></tr>`}).join('')||empty(7);
 $('#expenseTable').innerHTML=S.expenses.slice().reverse().map(x=>`<tr><td>${x.date}</td><td>${x.cat}</td><td>${esc(x.desc)}</td><td>${rp(x.amount)}</td></tr>`).join('')||empty(4);
 $('#profitTable').innerHTML=S.batches.map(b=>{let ss=S.sales.filter(x=>x.batchId==b.id),om=ss.reduce((a,x)=>a+x.total,0),q=ss.reduce((a,x)=>a+x.qty,0),hc=q*b.hppkg,l=om-hc;return `<tr><td>${b.code}</td><td>${kg(b.output)}</td><td>${kg(q)}</td><td>${rp(om)}</td><td>${rp(hc)}</td><td>${rp(l)}</td><td>${om?(l/om*100).toFixed(1):0}%</td></tr>`}).join('')||empty(7);
 $('#report').innerHTML=`<div><span>Total omzet</span><strong>${rp(sales)}</strong></div><div><span>HPP terjual</span><strong>${rp(cogs)}</strong></div><div><span>Laba kotor penjualan</span><strong>${rp(sales-cogs)}</strong></div><div><span>Pengeluaran umum</span><strong>${rp(other)}</strong></div><div><span>Laba bersih jurnal</span><strong>${rp(sales-cogs-other)}</strong></div><div><span>Total batch</span><strong>${S.batches.length}</strong></div>`;
 $('#recent').innerHTML=S.batches.slice(-5).reverse().map(b=>`<div style="padding:10px;border-bottom:1px solid #eee"><b>${b.code}</b> · ${esc(b.rawName)}<br><small>${b.date} · ${kg(b.output)} · HPP ${rp(b.hppkg)}/kg · susut ${b.lossPct.toFixed(1)}%</small></div>`).join('')||'Belum ada batch.';
}
function empty(n){return `<tr><td colspan="${n}" style="text-align:center;color:#929a93">Belum ada data</td></tr>`}
function go(p){$$('.page').forEach(x=>x.classList.toggle('active',x.id===p));$$('nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===p));$('#title').textContent=p==='raw'?'Bahan Baku':p==='batch'?'Produksi Batch':p==='finished'?'Barang Jadi':p[0].toUpperCase()+p.slice(1);$('#modal').classList.remove('show')}
$$('nav button').forEach(x=>x.onclick=()=>go(x.dataset.page));$('#quick').onclick=()=>$('#modal').classList.add('show');$$('#modal [data-go]').forEach(x=>x.onclick=()=>go(x.dataset.go));
$('#rawForm').onsubmit=e=>{e.preventDefault();let x=Object.fromEntries(new FormData(e.target));S.raw.push({id:Date.now(),date:x.date,name:x.name,qty:+x.qty,price:+x.price,supplier:x.supplier});save();e.target.reset();e.target.date.value=today;alert('Stok bahan baku ditambahkan.')}
$('#batchForm').onsubmit=e=>{e.preventDefault();let x=Object.fromEntries(new FormData(e.target)),r=S.raw.find(z=>z.id==x.rawId);if(!r||+x.inputQty>r.qty)return alert('Stok bahan baku tidak mencukupi.');if(+x.outputQty<=0)return alert('Hasil produksi harus lebih dari 0.');let material=+x.inputQty*r.price,total=material+(+x.labor||0)+(+x.energy||0)+(+x.other||0),loss=+x.inputQty-+x.outputQty;let bnum=S.batches.length+1;S.batches.push({id:Date.now(),code:`BCH-${x.date.slice(0,4)}-${String(bnum).padStart(3,'0')}`,date:x.date,rawId:r.id,rawName:r.name,input:+x.inputQty,output:+x.outputQty,loss,lossPct:loss/+x.inputQty*100,totalHpp:total,hppkg:total/+x.outputQty,labor:+x.labor||0,energy:+x.energy||0,other:+x.other||0,note:x.note});r.qty-=+x.inputQty;save();e.target.reset();e.target.date.value=today;alert('Batch produksi berhasil dibuat.')}
$('#salesForm').onsubmit=e=>{e.preventDefault();let x=Object.fromEntries(new FormData(e.target)),b=batch(x.batchId),s=sold(b.id);if(!b||+x.qty>b.output-s)return alert('Stok batch tidak mencukupi.');S.sales.push({date:x.date,batchId:b.id,customer:x.customer,qty:+x.qty,price:+x.price,total:+x.qty*+x.price,status:x.status});save();e.target.reset();e.target.date.value=today;alert('Penjualan berhasil dicatat.')}
$('#expenseForm').onsubmit=e=>{e.preventDefault();let x=Object.fromEntries(new FormData(e.target));S.expenses.push({...x,amount:+x.amount});save();e.target.reset();e.target.date.value=today;alert('Pengeluaran berhasil dicatat.')}
$('#backup').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(S,null,2)],{type:'application/json'}));a.download='inzaki-charcoal-backup.json';a.click()}
$('#reset').onclick=()=>{if(confirm('Hapus semua data?')){localStorage.removeItem(K);location.reload()}};render();