/* INZAKI GROUP — ikon, banner halaman, dan animasi (tidak mengubah data/logika aplikasi) */
(function(){
const S=b=>`<svg viewBox="0 0 40 40">${b}</svg>`;
const IC={kelapa:S('<circle cx="20" cy="20" r="16" fill="#7A5230"/><circle cx="20" cy="20" r="11.5" fill="#F4F1E4"/><circle cx="20" cy="20" r="5.5" fill="#CFE6D8"/><circle cx="14" cy="9" r="1.6" fill="#4B321C"/><circle cx="20" cy="7.5" r="1.6" fill="#4B321C"/>'),batok:S('<path d="M5 20A15 15 0 0 0 35 20Z" fill="#7A5230"/><ellipse cx="20" cy="20" rx="15" ry="4.5" fill="#A7743F"/><ellipse cx="20" cy="20" rx="11" ry="2.6" fill="#5A3B20"/>'),kopra:S('<rect x="4" y="19" width="19" height="11" rx="4" fill="#F4F1E4" stroke="#CFC7A8" transform="rotate(-12 13 24)"/><rect x="17" y="12" width="19" height="11" rx="4" fill="#FBF9EE" stroke="#CFC7A8" transform="rotate(10 26 17)"/><rect x="9" y="27" width="20" height="9" rx="4" fill="#EFEBD9" stroke="#CFC7A8"/>'),arang:S('<rect x="4" y="18" width="18" height="14" rx="4" fill="#2B2F2D" transform="rotate(-8 13 25)"/><rect x="18" y="12" width="17" height="15" rx="4" fill="#3A3F3C" transform="rotate(9 26 19)"/><path d="M20 4c3 4-2 6 0 9 3-1 5-4 3-9z" fill="#E3B94F"/><path d="M8 27l6-2M24 19l6 2" stroke="#6B726E" stroke-width="1.5" stroke-linecap="round"/>'),coin:S('<circle cx="20" cy="20" r="15" fill="#E3B94F"/><circle cx="20" cy="20" r="10.5" fill="none" stroke="#B8891F" stroke-width="2"/><path d="M20 13v14M16.5 17c0-2 7-2 7 0s-7 2-7 4 7 2 7 0" stroke="#8F6510" stroke-width="2" fill="none" stroke-linecap="round"/>'),chart:S('<rect x="5" y="22" width="7" height="13" rx="2" fill="#8FD6A8"/><rect x="16.5" y="14" width="7" height="21" rx="2" fill="#3DB37B"/><rect x="28" y="6" width="7" height="29" rx="2" fill="#22C55E"/>'),bill:S('<path d="M9 4h22v32l-4-3-3.5 3-3.5-3-3.5 3-3.5-3-4 3z" fill="#EDEFEA" stroke="#9BB0A2" stroke-width="2"/><path d="M14 12h12M14 18h12M14 24h7" stroke="#16A34A" stroke-width="2.4" stroke-linecap="round"/>')};
const icon=(t,o)=>{t=(t||'').toLowerCase();for(const k of (o||['batok','kelapa','kopra','arang']))if(t.includes(k))return `<span class="ic">${IC[k]}</span>`;return ''};
function decorate(){
  document.querySelectorAll('.stock-card').forEach(c=>{if(!c.querySelector('.ic'))c.insertAdjacentHTML('afterbegin',icon(c.querySelector('.stock-card-name')?.textContent))});
  document.querySelectorAll('.line-card-head').forEach(c=>{if(!c.querySelector('.ic'))c.insertAdjacentHTML('afterbegin',icon(c.textContent,['arang','kopra','batok','kelapa']))});
  document.querySelectorAll('.flow-node').forEach(c=>{if(!c.querySelector('.ic'))c.insertAdjacentHTML('afterbegin',icon(c.querySelector('b')?.textContent))});
}
const PG={raw:['kelapa','Bahan Baku','Catat pembelian kelapa dan batok beserta biaya angkut'],batch:['arang','Produksi Batch','Catat hasil produksi dan pantau rendemen tiap batch'],finished:['kopra','Barang Jadi','Stok kopra dan arang siap jual'],sales:['coin','Penjualan','Faktur, pelanggan, dan status pembayaran'],expenses:['bill','Pengeluaran','Biaya operasional di luar bahan baku'],debts:['bill','Hutang','Pantau cicilan dan jatuh tempo'],finance:['coin','Keuangan','Catat pemasukan dan pengeluaran, pantau kas dan arus dana'],reports:['chart','Laba & Laporan','Ringkasan omzet, HPP, dan laba bersih']};
for(const k in PG){const p=document.getElementById(k);if(p&&!p.querySelector('.page-banner'))p.insertAdjacentHTML('afterbegin',`<div class="page-banner"><span class="ic">${IC[PG[k][0]]}</span><div><b>${PG[k][1]}</b><small>${PG[k][2]}</small></div></div>`)}
const hd=document.getElementById('heroDate');if(hd)hd.textContent=new Date().toLocaleDateString('id-ID',{weekday:'long',day:'numeric',month:'long',year:'numeric'});
const rm=matchMedia('(prefers-reduced-motion:reduce)').matches;
function stagger(p){p.querySelectorAll('.cards,.stock-cards,.stock-grid-2,#lineStatsCards,#insightList,#batchLossList,.report,.flow-diagram,.recent-list').forEach(c=>[...c.children].forEach((e,i)=>e.style.setProperty('--i',i+1)));p.querySelectorAll('.panel').forEach((e,i)=>e.style.setProperty('--i',i+1));p.querySelectorAll('tbody').forEach(t=>[...t.children].forEach((e,i)=>e.style.setProperty('--i',i)))}
function count(p){if(rm)return;p.querySelectorAll('.cards b,.report strong,.stock-card-qty').forEach(el=>{if(el.children.length||el.dataset.busy)return;const src=el.textContent,m=src.match(/(\d[\d.]*)(?:,(\d+))?/);if(!m)return;const d=(m[2]||'').length,v=parseFloat(m[1].replace(/\./g,'')+'.'+(m[2]||'0')),t0=performance.now();el.dataset.busy=1;(function s(t){const q=Math.min((t-t0)/1000,1);el.textContent=src.replace(m[0],(v*(1-Math.pow(1-q,3))).toLocaleString('id-ID',{minimumFractionDigits:d,maximumFractionDigits:d}));if(q<1)requestAnimationFrame(s);else{el.textContent=src;delete el.dataset.busy}})(t0)})}
function play(){const p=document.querySelector('.page.active');if(!p)return;decorate();stagger(p);p.classList.remove('anim');void p.offsetWidth;p.classList.add('anim');count(p);setTimeout(()=>p.classList.remove('anim'),1800)}
let raf;new MutationObserver(()=>{cancelAnimationFrame(raf);raf=requestAnimationFrame(decorate)}).observe(document.querySelector('main'),{childList:true,subtree:true});
document.querySelectorAll('nav button').forEach(b=>b.addEventListener('click',()=>setTimeout(play,40)));
const lo=document.getElementById('loadingOverlay');
if(lo&&!lo.classList.contains('hide'))new MutationObserver((m,o)=>{if(lo.classList.contains('hide')){o.disconnect();setTimeout(play,150)}}).observe(lo,{attributes:true,attributeFilter:['class']});else setTimeout(play,300);
decorate();
})();
