-- Jalankan di Supabase → SQL Editor (sekali saja). Aman dijalankan ulang.

-- 1) Tabel buku kas untuk halaman Keuangan
create table if not exists public.cashbook (
  id bigint generated by default as identity primary key,
  date date not null default current_date,
  type text not null check (type in ('in','out')),
  cat text not null,
  note text,
  amount numeric not null check (amount > 0),
  created_at timestamptz default now()
);
alter table public.cashbook enable row level security;
drop policy if exists "cashbook baca" on public.cashbook;
drop policy if exists "cashbook admin" on public.cashbook;
create policy "cashbook baca"  on public.cashbook for select using (true);
create policy "cashbook admin" on public.cashbook for all to authenticated using (true) with check (true);

-- 2) OPSIONAL: jika tombol Hapus/Lunas pada penjualan (piutang) menampilkan
--    "Data tidak terhapus di server", tambahkan kebijakan ini (hapus tanda -- di depan):
-- drop policy if exists "sales hapus" on public.sales;
-- create policy "sales hapus" on public.sales for delete to authenticated using (true);
-- drop policy if exists "sales ubah" on public.sales;
-- create policy "sales ubah" on public.sales for update to authenticated using (true) with check (true);
